### ISSUE TITLE
Sensor MA 10251

### ISSUE THREAD

**Issue by ppiwowar** [PlusPlus-ua/ha_mobilealerts#5]
Great integration !! Has worked on the spot. 
A little fine-tuning kindly requested for MA 10251 (or MA 10250), though.
Humidity is 10-bit (not 9-bit). So instead of 98.7 % we get 47.5% (98.7-47.5=51.2)
This difference is always 51.2 (or 512 in integer representation).
Other Humidity sensors I have (e.g. MA 10200) are XY.0 precision, so 8-bit precision is enough to cover 0=100% range.
This sensor MA 10251 entity is represented by name:
sensor.professional_thermo_hygro_sensor_0e44a09a67f9_humidity
A sensor MA 10200 is represented by:
sensor.temperature_humidity_03009426e837_humidity 
Any ideas ?

**Comment by PlusPlus-ua** [comment]
Hi, thank you for kind words and for bug report.

There was really used 9-bit range instead of 10-bit.

I'll try to fix it ASAP. 

Unfortunately, I have to work now in semi-constant blackouts (I'm from Ukraine). So, most of the time when my computer is available and online I spend for my main work, not hobby.

**Comment by ppiwowar** [comment]
Thanks! Take your time & stay safe!
I would appreciate a fix, as I am total HA/Python newbie, so I would take me tones of time.
Ще не вмерла Україна!

**Comment by PlusPlus-ua** [comment]
Resolved, please try to update.

**Comment by ppiwowar** [comment]
Works like a charm!
Thank you! Велике спасибі !
